### PR TITLE
Report error when fails to write mock file

### LINKED ISSUE #189: Fails silently when destination directory does not exist
When the path passed to `--destination` option has non-existent parent directory, mockolo fails to create mock file but it cannot be read from the log message. 

```
❯ mockolo --sourcedirs Path/To/SourceDir --destination /NonexistentDirectory/Mocks.swift
Start...
["Process input mock files..."]
["Took", 4.1961669921875e-05]
["Process source files and generate an annotated/protocol map..."]
["Took", 0.023231029510498047]
["Resolve inheritance and generate unique entity models..."]
["Took", 0.0008450746536254883]
["Render models with templates..."]
["Took", 0.0002319812774658203]
["Write the mock results and import lines to", "/NonexistentDirectory/Mocks.swift"]
["Took", 0.0001609325408935547]
["TOTAL", 0.024510979652404785]
["#Protocols = 3, #Annotated protocols = 3, #Parent mock classes = 0, #Final mock classes = 3, File LoC = 77"]
["Done. Exiting program."]
Done.
```

I think it would be less confusing if error message like `destination directory /NonexistentDirectory does not exist` is shown in this situation.

If it's OK, I'd be happy to create a PR for this. Please close this issue if the current behavior is intentional for some reason.

### PR DESCRIPTION
**Pull request by maiyama18**
Close #189 

This PR makes mockolo command report error in log message and finish with non-zero exit code when it fails to create mock file. Change of the log message for that situation is shown below.

### before

```
❯ mockolo --sourcedirs Path/To/SourceDir --destination /NonexistentDirectory/Mocks.swift
Start...
["Process input mock files..."]
["Took", 4.1961669921875e-05]
["Process source files and generate an annotated/protocol map..."]
["Took", 0.023231029510498047]
["Resolve inheritance and generate unique entity models..."]
["Took", 0.0008450746536254883]
["Render models with templates..."]
["Took", 0.0002319812774658203]
["Write the mock results and import lines to", "/NonexistentDirectory/Mocks.swift"]
["Took", 0.0001609325408935547]
["TOTAL", 0.024510979652404785]
["#Protocols = 3, #Annotated protocols = 3, #Parent mock classes = 0, #Final mock classes = 3, File LoC = 77"]
["Done. Exiting program."]
Done.
```

## after

```
❯ mockolo --sourcedirs Path/To/SourceDir --destination /NonexistentDirectory/Mocks.swift
Start...
["Process input mock files..."]
["Took", 6.496906280517578e-05]
["Process source files and generate an annotated/protocol map..."]
["Took", 0.07189595699310303]
["Resolve inheritance and generate unique entity models..."]
["Took", 7.808208465576172e-05]
["Render models with templates..."]
["Took", 9.894371032714844e-06]
["Write the mock results and import lines to", "/NonexistentDirectory/Mocks.swift"]
Mockolo/Executor.swift:213: Fatal error: Generation error: Error Domain=NSCocoaErrorDomain Code=4 "The folder “Mocks.swift” doesn’t exist." UserInfo={NSFilePath=/NonexistentDirectory/Mocks.swift, NSUserStringVariant=Folder, NSUnderlyingError=0x600003ce90e0 {Error Domain=NSPOSIXErrorDomain Code=2 "No such file or directory"}}
zsh: trace trap  .build/arm64-apple-macosx/debug/mockolo --sourcedirs Sources --destination
```

### CODE REVIEW

File: Sources/MockoloFramework/Operations/OutputWriter.swift [hunk 1]
```diff
@@ -46,7 +46,7 @@ func write(candidates: [(String, Int64)],
         return ret
     }
 
-    _ = try? ret.write(toFile: outputFilePath, atomically: true, encoding: .utf8)
+    _ = try ret.write(toFile: outputFilePath, atomically: true, encoding: .utf8)
```
Comment (maiyama18) [inline Sources/MockoloFramework/Operations/OutputWriter.swift:49]: There are several options to resolve #189, but I thought that not ignoring write error is more versatile than others. Since mockolo command's primary purpose is creating mock file, it seems natural to finish whole process and report this error as the cause when failed to write mock file.

File: Tests/MockoloTestCase.swift [hunk 2]
```diff
@@ -54,18 +54,35 @@ class MockoloTestCase: XCTestCase {
         }
     }
 
-    func verify(srcContent: String, mockContent: String? = nil, dstContent: String, header: String = "", declType: DeclType = .protocolType, useTemplateFunc: Bool = false, useMockObservable: Bool = false, testableImports: [String] = [], allowSetCallCount: Bool = false, mockFinal: Bool = false, enableFuncArgsHistory: Bool = false, concurrencyLimit: Int? = 1, disableCombineDefaultValues: Bool = false) {
+    func verify(srcContent: String, mockContent: String? = nil, dstContent: String, header: String = "", declType: DeclType = .protocolType, useTemplateFunc: Bool = false, useMockObservable: Bool = false, testableImports: [String] = [], allowSetCallCount: Bool = false, mockFinal: Bool = false, enableFuncArgsHistory: Bool = false, outputFilePath: String? = nil, concurrencyLimit: Int? = 1, disableCombineDefaultValues: Bool = false) {
+        let outputFilePath = outputFilePath ?? dstFilePath
```
Comment (uhooi) [inline Tests/MockoloTestCase.swift:58]: [nits]
The following naming seems better:
`outputFilePath` → `dstFilePath`
`dstFilePath` → `defaultDstFilePath`

Comment (maiyama18) [reply Tests/MockoloTestCase.swift]: @uhooi Thanks for your comment! I totally agree with that. Fixed by https://github.com/uber/mockolo/pull/193/commits/ee1f00fc7ac31105e8e8c910c7895e7b000545c4 .

**Review by uhooi — APPROVED** [review]
